### ISSUE TITLE
Should testbuilder trigger other testbuilder?

### ISSUE THREAD

**Issue by zhouchengming1** [mikeferguson/buildbot-ros#73]
I see the debbuiler will trigger other debbuilder that depend on it ,   so should testbuilder also trigger these repos ?

**Comment by mikeferguson** [comment]
Generally, no.

The reason that we rebuild all downstream Debian builders is because ROS developers generally do a terrible job of assuring ABI compatibility (compared to say, Ubuntu themselves). In addition, when inserting the new package into the Debian repo, the downstream packages will generally be invalidated and removed as well. Therefore, when you release/build a new version of a Debian package, you really have to trigger downstream things too, or those packages will be missing/broken.

testbuilder jobs are completely different. You are either testing a recent commit, or a pull request, to make sure that it builds and passes tests. In fact, there is no value to triggering downstream package/repo tests, since those tests will actually use the last Debian build of this package.

**Comment by zhouchengming1** [comment]
I think about a scenario:
If repo A1 -> A1.deb, then B1 test passed,  and debbuild -> B1.deb.
So B1.deb is ok when depend is A1.deb.
But when A1 changes to A2, test passed -> A2.deb,   then trigger downstream B1 debbuild -> B2.deb.
The created B2.deb doesn't pass tests actually.   So if I install A2.deb and B2.deb,  B2.deb may have  runtime error ?

**Comment by zhouchengming1** [comment]
I think you are  right that   upstream testbuild doesn't need to trigger downstream testbuild, because downstream test will use the last Debian build of upstream packages.

I only worry that the current debbuilder trigger method is not enough to make sure created downstream debian packages are correct when run on user's machine.

**Comment by mikeferguson** [comment]
The test/deb builds are entirely separate, except that the test builds may rely on other repositories deb builds. When doing a "test" build, you're only testing *internal* to that package -- none of the ROS farms out there support downstream testing AFAIK.

Side Note: there have been various pre-release testing mechanisms over time in ROS (which is basically the idea that before I release A2, I check to see if all my downstream depends still build), but I'm not sure their status.

This is certainly a challenge for developers, especially as packages gets a longer downstream tail. This is why most ROS developers minimize avoid, as much as possible, API/ABI breaking and other large changes within a ROS distribution. If I have a "stable" release in Kinetic, then users of my package in Kinetic can rest assured that it will be rare for a downstream problem. I can then put bigger changes into my first/early releases in a future distribution (such as lunar or melodic).
